name: Hourly AQI Data Ingestion

on:
  schedule:
    - cron: '0 * * * *' # Har ghante khud chale ga
  workflow_dispatch:      # Is se aap button daba kar khud bhi chala saktay hain

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install "hopsworks==4.2.*"
          pip install pyarrow pandas scikit-learn joblib numpy python-dotenv
          
      - name: Run Ingestion Script
        env:
          HOPSWORKS_KEY: ${{ secrets.HOPSWORKS_KEY }}
        run: python data_pipeline/backfills.py
